### ISSUE TITLE
Create API

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#17]
**description**
Create new module witch return json using [django-rest-framework](http://www.django-rest-framework.org/).

**todo**
- [ ] Init new api
- [ ] Install Django-Rest framework
- [ ] Create DB test
- [ ] Fill the DB
