### ISSUE TITLE
Template for the game

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#24]
**description**
Create html page to play.

**todo**
- [x] Game board (Centre)
- [x] Hand (Bottom)
- [x] Name player (right of the hand)
- [x] Button validate propose (right of the hand)
