### ISSUE TITLE
Create model for the game

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#27]
**description**
Have to save everything in database

**todo**
- [x] Create a draw.io to define relation
- [x] Create models (see bottom)
- [x] Add index when nececery

**definition**
- << Enum >> Token:
  - value: positiveInt
  - letter: char
- Deck:
  - ID_deck
  - Token: Token
- Player:
  - ID_player: UUID
  - Name: String(100)
- Game:
  - UUID: UUID
  - GameBoard: Arrayfield
  - Player1: Player
  - Player2: Player
  - Deck: Deck
  - Hand_player_1: Arrayfield
  - Hand_player_2: Arrayfield

How to fill the Deck:
- 0 point : Joker ×2 (appelés en français jokers ou lettres blanches)
- 1 point : E ×15, A ×9, I ×8, N ×6, O ×6, R ×6, S ×6, T ×6, U ×6, L ×5
- 2 points : D ×3, M ×3, G ×2
- 3 points : B ×2, C ×2, P ×2
- 4 points : F ×2, H ×2, V ×2
- 8 points : J ×1, Q ×1
- 10 points : K ×1, W ×1, X ×1, Y ×1, Z ×1

---
> (1) arrayfield
https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#arrayfield

**Comment by imimoun** [comment]
For now, we want to force the players to choose specific words. As we do not have to use a deck.

**Comment by imimoun** [comment]
We have to write the liste of the word we want to give to the players.

**Comment by imimoun** [comment]
![model - scrabble 1](https://user-images.githubusercontent.com/38384550/40589699-c639d6f6-61fa-11e8-81a4-fb9d9d7aa667.png)
