### ISSUE TITLE
Update scrabble app to play basicly

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#31]
**description**
We have to run an useful app.
Start with the beginning.

**todo**
- [ ] Manually create Player_1 and Player_2
- Create basic login page
  - [ ] Choose your name and create/join Game.
- Init game:
  - [ ] Fill deck with #29
- Play turn:
  - [ ] Each begin of the turn, player takes enough token to begin with 7
  - [ ] input for each token with form submit (on board and on hand)
  - [ ] Send an update when it's the turn of the other player
