### ISSUE TITLE
Use "bootstrap 4 Col Portfolio" as first page

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#33]
**description**
We have to use a first page witch redirect the user to each project.
To do that, we will use a new bootstrap.

**todo**
- [x] Install "bootstrap 4 Col Portfolio"
- [x] Use it as a main page
- [x] Add each first page projet to its.

**Comment by imimoun** [comment]
Done.
