### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#4]
**description**
Help people interested in this repository understand your project by adding a README.

**todo**
- [x] Initialize empty README
- [x] Create doc/Import project tell the way to import this project
  - Create virtual envs python 3
  - Run virtualenvs
  - Clone in folder project
  - migrate
  - runserver
- [x] Definition of the project
- [x] Add shield. https://shields.io
