### ISSUE TITLE
Configure Travis

### ISSUE THREAD

**Issue by imimoun** [imimoun/mysitedj2_0#7]
**description**
Travis CI is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub.

**todo**
- Config travis
  - [x] Create settings file for travis
  - [x] Create .travis.yml
- On README.md add 2 tags:
  - [x] [![Build Status](https://travis-ci.org/imimoun/mysitedj2_0.svg?branch=master)](https://travis-ci.org/imimoun/mysitedj2_0)
  - [x] [![Build Status](https://travis-ci.org/imimoun/mysitedj2_0.svg?branch=dev)](https://travis-ci.org/imimoun/mysitedj2_0)

**Comment by imimoun** [comment]
It is hard to use travis with SQLitle3, we have to move to posgresql.
